version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432

    env_file:
      - ./webchat-backend/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/name/
    volumes:
      - data-volume:/var/lib/postgresql/data

  backend:
    restart: always
    environment:
      - POSTGRES_HOST=postgres
    container_name: backend
    depends_on:
      - postgres
    build:
      context: ./webchat-backend
    ports:
      - 3333:3333

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: ./webchat-frontend
    ports:
      - 3000:3000

volumes:
  data-volume: